spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/sokker_db}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:stojke}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=false
server.port=8090
debug=false
logging.level.org.springframework=INFO
logging.level.org.velja=INFO
logging.level.org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener=OFF

sokker.nt-team-id=39
sokker.nt21-team-id=439
sokker.nt-country-code=39

sokker.scouting-usernames=veljizao,vacke
sokker.scouting-scan-usernames=veljizao
sokker.scouting-country-code=39
sokker.scouting-max-age=21
sokker.scouting-threads=5