
spring.datasource.url=jdbc:h2:mem:footballmanager
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
server.port=8090
debug=false
logging.level.org.springframework=INFO
logging.level.org.velja=INFO
logging.level.org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener=OFF

sokker.nt-manager-usernames=dzungla,veljizao
sokker.nt-team-id=39
sokker.nt-country-code=39
